language: r
sudo: false
cache: packages
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode8.2
      before_install:
        - brew install curl
        - brew link --force curl
      latex: false
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'
    - os: osx
      osx_image: xcode7.3
      latex: false
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'

r_packages:
- covr
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

before_install: |
  mkdir ~/.R
  cat <<EOF > ~/.R/Makevars
  CXX=g++-4.9
  CXX1X=g++-4.9
  CXX1XSTD=-std=c++11

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
